baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: $PRIMARY_SITE_NAME
primary: true
siteGroup: 8cad3e8a-2b40-415c-9a8f-f7d3b661fd0f # craft-vite
sortOrder: 1
